# Copyright (C) 2013, 2021 by Massimo Lauria <lauria@kth.se>
#
# Created   : "2013-07-24, 01:53 (CEST) Massimo Lauria"
# Time-stamp: "2021-02-16, 15:49 (CET) Massimo Lauria"
#
#
## Makefile for the cnftools utilities. 
#
# Some build parameters follows. You should not change anything but
# these few parameters.


# --------- Project dependent rules ---------------
PKGNAME=cnf2kcnf
TARGET=cnf2kcnf
TIME=$(shell date +%Y.%m.%d-%H.%M)

#
# Optimization and debug flags
#
DEBUG=-g 
PROFILE=-pg
OPTIMIZATION=

# 
# compilers and language standards
#
CC=gcc
C_STANDARD=-std=c99
CXX=g++
CXX_STANDARD=-std=c++11
CXX_STDLIB=
TAGS=gtags # etags ctags
LINK.o=$(LINK.cc)

# -------- Nothing to see below this line -----------
#
# All build parameters are above this comment. There is no need to
# change anything below unless you are developing
#

all: ${TARGET}

.PHONY: all clean test check-syntax tags



#
# Compilation variables
#
SRC=./
INC=-I${SRC}

#
# Cppunit Test 
#
CPPUNITLIBS=$(shell cppunit-config --libs)


OTHERFLAGS=-finline-functions -fno-builtin --pedantic --pedantic-errors -Wall
CFLAGS=${OPTIMIZATION} ${DEBUG} ${PROFILE} ${OTHERFLAGS}   ${C_STANDARD}
CXXFLAGS=${OPTIMIZATION} ${DEBUG} ${PROFILE} ${OTHERFLAGS} ${CXX_STDLIB} ${CXX_STANDARD} ${CUCFLAGS}
LDFLAGS=${DEBUG} ${PROFILE}
LDLIBS=${CPPUNITLIBS}



#
# Indexing source code
#
TAGFILES=GPATH GRTAGS GSYMS GTAGS tags TAGS ID

#
# --------- Object files
#
OBJS=cnf2kcnf.o testbasic.o testparser.o testcnf2kcnf.o testcode.o cnftools.o cnf.o dimacs_io.o
cnf2kcnf: cnf2kcnf.o cnftools.o cnf.o dimacs_io.o
testcode: testcode.o testbasic.o testparser.o testcnf2kcnf.o cnftools.o cnf.o dimacs_io.o

# --------- Default rules -------------------------
clean:
	@-rm -f  ${TARGET}
	@-rm -f  gmon.out
	@-rm -f  ${OBJS}
	@-rm -f  ${DEPS}
	@-rm -fr *.dSYM
	@-rm -f ${TAGFILES}

tags:
	$(TAGS) -I .

check-syntax:
	$(CXX) ${CXXFLAGS} -o - -S ${CHK_SOURCES} >/dev/null

pkg:
	@make clean
	@echo "Packaging $(PKGNAME).$(TIME).tar.gz"
	@cd .. && \
	tar cfz $(PKGNAME).$(TIME).tar.gz $(NAME) 2> /dev/null

test: testcode
	@echo "Running tests on code"
	./testcode

#
# files
#
SRCS		= $(OBJS:.o=.c)
DEPS		= $(SRCS:.c=.d)


# ------- Default build rules
%.o: %.c %.d
	$(CC) ${CFLAGS} -c $< -o $@

%.o: %.cc %.d
	$(CXX) ${CXXFLAGS} -c $< -o $@

%.d: %.c
	$(strip $(SHELL) -ec '$(CC) -MM $(CFLAGS) $< \
			              | sed '\''s/$*\\.o[ :]*/& $@/g'\'' > $@')

%.d: %.cc
	$(strip $(SHELL) -ec '$(CXX) -MM $(CXXFLAGS) $< \
			              | sed '\''s/$*\\.o[ :]*/& $@/g'\'' > $@')


# Autogenerated prerequisites
-include $(DEPS)
